version: "2"

volumes:
    db_data:

services:
    php-shop-demo:
        build: ./nginx
        ports:
            - 8181:8000
        volumes:
            - ./src:/usr/data
            - /usr/data/vendor
            - /usr/data/var
        privileged: true
        environment:
            - TOKEN=Yl_utY2wIV8sfCCsekTHhA
            - HOST=my-webserver
            - REALM=us0
            - BUYMETRIC=ecointet.shop
            - TYPE=shoes
            - CUSTOMER=justdoit
